services:
  - type: web
    name: music-box
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/ping
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
